---
title: "Exercise 1_1: Package Installation"
subtitle: 'Advanced Geospatial Data Processing for Social Scientists'
author: Dennis Abel & Stefan Jünger
format: 
  html:
    embed-resources: true
    code-copy: true
editor: visual
callout-icon: false
callout-appearance: minimal
---

### Exercises

This is the first exercise in this workshop, and it is relatively easy and short. Its purpose is to get used to this exercise format and, more importantly, to install all necessary packages for this course.

And here comes our very first exercise (which is not very spatial...):

::: callout-note
## `r emo::ji("weight_lifting_man")` Exercise 1

Please install all packages that are listed at the end of the Introduction slides ("1_Introduction.html").
:::

::: {.callout-caution collapse="true"}
## `r emo::ji("bulb")` Tip

We often recommend using the `easypackages` packages, which can be installed with the command `install.packages("easypackages")`. After loading the package with `library(easypackages)` you can load *and* install packages with the command `easypackages::packages("fancy_package_1", "fancy_package_2", ...)`.
:::

That's it. Please notify us if there are any issues with installing the packages or, more generally, your `R` installation.

...oh, and if you got some time left:

::: callout-note
## `r emo::ji("weight_lifting_man")` OPTIONAL: Exercise 2

Visit the website <https://thetruesize.com/>.
:::

### Solutions

::: {.callout-tip collapse="true"}
## `r emo::ji("white_check_mark")` Solution 1

```{r}
#| eval: false
library(easypackages)

easypackages::packages(
  "blackmarbler",
  "dplyr",
  "ggplot2",
  "ggrepel",
  "ggspatial",
  "randomForest",
  "readr",
  "scales",
  "sf",
  "stars",
  "terra",
  "tidyterra",
  "tigris",
  "units"
) 
```
:::
